version: '3.8'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - backend/.env
    volumes:
      - static:/app/static
      - prisma:/app/prisma
  frontend:
    build:
      context: ./frontend
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
volumes:
  static:
  prisma:
