on: [push, pull_request]
jobs:
  test-express:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.15.1
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.1

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Run code coverage test
        run: npm test -- --coverage
        working-directory: ./backend

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: backend
          slug: MarcelHor/tul-plant
